openapi: 3.0.3
info:
  title: interactions API
  description: Owner or admin management of users interactions.
  version: 1.1.4
paths:
  /orgs/{org}/interaction-limits:
    get:
      summary: Get interaction restrictions for an organization
      description: >-
        Shows which type of GitHub user can interact with this organization and
        when the restriction expires. If there is no restrictions, you will see
        an empty response.
      tags:
        - interactions
      operationId: interactions/get-restrictions-for-org
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/rest/interactions/orgs#get-interaction-restrictions-for-an-organization
      parameters:
        - $ref: '#/components/parameters/org'
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                title: Interaction Limits
                description: Interaction limit settings.
                type: object
                properties:
                  limit:
                    $ref: '#/components/schemas/interaction-group'
                  origin:
                    type: string
                    example: repository
                  expires_at:
                    type: string
                    format: date-time
                    example: '2018-08-17T04:18:39Z'
                required:
                  - limit
                  - origin
                  - expires_at
                additionalProperties: false
              examples:
                default:
                  $ref: '#/components/examples/interaction-limit-response'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: interactions
        subcategory: orgs
      x-stackQL-resource: orgs
    put:
      summary: Set interaction restrictions for an organization
      description: >-
        Temporarily restricts interactions to a certain type of GitHub user in
        any public repository in the given organization. You must be an
        organization owner to set these restrictions. Setting the interaction
        limit at the organization level will overwrite any interaction limits
        that are set for individual repositories owned by the organization.
      tags:
        - interactions
      operationId: interactions/set-restrictions-for-org
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/rest/interactions/orgs#set-interaction-restrictions-for-an-organization
      parameters:
        - $ref: '#/components/parameters/org'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/interaction-limit'
            examples:
              default:
                value:
                  limit: collaborators_only
                  expiry: one_month
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/interaction-limit-response'
              examples:
                default:
                  $ref: '#/components/examples/interaction-limit-response'
        '422':
          $ref: '#/components/responses/validation_failed'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: interactions
        subcategory: orgs
      x-stackQL-resource: orgs
    delete:
      summary: Remove interaction restrictions for an organization
      description: >-
        Removes all interaction restrictions from public repositories in the
        given organization. You must be an organization owner to remove
        restrictions.
      tags:
        - interactions
      operationId: interactions/remove-restrictions-for-org
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/rest/interactions/orgs#remove-interaction-restrictions-for-an-organization
      parameters:
        - $ref: '#/components/parameters/org'
      responses:
        '204':
          description: Response
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: interactions
        subcategory: orgs
      x-stackQL-resource: orgs
  /repos/{owner}/{repo}/interaction-limits:
    get:
      summary: Get interaction restrictions for a repository
      description: >-
        Shows which type of GitHub user can interact with this repository and
        when the restriction expires. If there are no restrictions, you will see
        an empty response.
      tags:
        - interactions
      operationId: interactions/get-restrictions-for-repo
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/rest/interactions/repos#get-interaction-restrictions-for-a-repository
      parameters:
        - $ref: '#/components/parameters/owner'
        - $ref: '#/components/parameters/repo'
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                title: Interaction Limits
                description: Interaction limit settings.
                type: object
                properties:
                  limit:
                    $ref: '#/components/schemas/interaction-group'
                  origin:
                    type: string
                    example: repository
                  expires_at:
                    type: string
                    format: date-time
                    example: '2018-08-17T04:18:39Z'
                required:
                  - limit
                  - origin
                  - expires_at
                additionalProperties: false
              examples:
                default:
                  $ref: '#/components/examples/interaction-limit-2'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: interactions
        subcategory: repos
      x-stackQL-resource: repos
    put:
      summary: Set interaction restrictions for a repository
      description: >-
        Temporarily restricts interactions to a certain type of GitHub user
        within the given repository. You must have owner or admin access to set
        these restrictions. If an interaction limit is set for the user or
        organization that owns this repository, you will receive a `409
        Conflict` response and will not be able to use this endpoint to change
        the interaction limit for a single repository.
      tags:
        - interactions
      operationId: interactions/set-restrictions-for-repo
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/rest/interactions/repos#set-interaction-restrictions-for-a-repository
      parameters:
        - $ref: '#/components/parameters/owner'
        - $ref: '#/components/parameters/repo'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/interaction-limit'
            examples:
              default:
                summary: Example request body
                value:
                  limit: collaborators_only
                  expiry: one_day
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/interaction-limit-response'
              examples:
                default:
                  $ref: '#/components/examples/interaction-limit-2'
        '409':
          description: Response
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: interactions
        subcategory: repos
      x-stackQL-resource: repos
    delete:
      summary: Remove interaction restrictions for a repository
      description: >-
        Removes all interaction restrictions from the given repository. You must
        have owner or admin access to remove restrictions. If the interaction
        limit is set for the user or organization that owns this repository, you
        will receive a `409 Conflict` response and will not be able to use this
        endpoint to change the interaction limit for a single repository.
      tags:
        - interactions
      operationId: interactions/remove-restrictions-for-repo
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/rest/interactions/repos#remove-interaction-restrictions-for-a-repository
      parameters:
        - $ref: '#/components/parameters/owner'
        - $ref: '#/components/parameters/repo'
      responses:
        '204':
          description: Response
        '409':
          description: Response
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: interactions
        subcategory: repos
      x-stackQL-resource: repos
  /user/interaction-limits:
    get:
      summary: Get interaction restrictions for your public repositories
      description: >-
        Shows which type of GitHub user can interact with your public
        repositories and when the restriction expires.
      tags:
        - interactions
      operationId: interactions/get-restrictions-for-authenticated-user
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/rest/interactions/user#get-interaction-restrictions-for-your-public-repositories
      responses:
        '200':
          description: Default response
          content:
            application/json:
              schema:
                title: Interaction Limits
                description: Interaction limit settings.
                type: object
                properties:
                  limit:
                    $ref: '#/components/schemas/interaction-group'
                  origin:
                    type: string
                    example: repository
                  expires_at:
                    type: string
                    format: date-time
                    example: '2018-08-17T04:18:39Z'
                required:
                  - limit
                  - origin
                  - expires_at
                additionalProperties: false
              examples:
                default:
                  $ref: '#/components/examples/interaction-limit-response'
        '204':
          description: Response when there are no restrictions
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: interactions
        subcategory: user
      x-stackQL-resource: user
    put:
      summary: Set interaction restrictions for your public repositories
      description: >-
        Temporarily restricts which type of GitHub user can interact with your
        public repositories. Setting the interaction limit at the user level
        will overwrite any interaction limits that are set for individual
        repositories owned by the user.
      tags:
        - interactions
      operationId: interactions/set-restrictions-for-authenticated-user
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/rest/interactions/user#set-interaction-restrictions-for-your-public-repositories
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/interaction-limit'
            examples:
              default:
                value:
                  limit: collaborators_only
                  expiry: one_month
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/interaction-limit-response'
              examples:
                default:
                  $ref: '#/components/examples/interaction-limit-user'
        '422':
          $ref: '#/components/responses/validation_failed'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: interactions
        subcategory: user
      x-stackQL-resource: user
    delete:
      summary: Remove interaction restrictions from your public repositories
      description: Removes any interaction restrictions from your public repositories.
      tags:
        - interactions
      operationId: interactions/remove-restrictions-for-authenticated-user
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/rest/interactions/user#remove-interaction-restrictions-from-your-public-repositories
      responses:
        '204':
          description: Response
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: interactions
        subcategory: user
      x-stackQL-resource: user
components:
  schemas:
    interaction-limit-response:
      title: Interaction Limits
      description: Interaction limit settings.
      type: object
      properties:
        limit:
          $ref: '#/components/schemas/interaction-group'
        origin:
          type: string
          example: repository
        expires_at:
          type: string
          format: date-time
          example: '2018-08-17T04:18:39Z'
      required:
        - limit
        - origin
        - expires_at
    interaction-limit:
      title: Interaction Restrictions
      description: Limit interactions to a specific type of user for a specified duration
      type: object
      properties:
        limit:
          $ref: '#/components/schemas/interaction-group'
        expiry:
          $ref: '#/components/schemas/interaction-expiry'
      required:
        - limit
    interaction-group:
      type: string
      description: >-
        The type of GitHub user that can comment, open issues, or create pull
        requests while the interaction limit is in effect.
      example: collaborators_only
      enum:
        - existing_users
        - contributors_only
        - collaborators_only
    interaction-expiry:
      type: string
      description: 'The duration of the interaction restriction. Default: `one_day`.'
      example: one_month
      enum:
        - one_day
        - three_days
        - one_week
        - one_month
        - six_months
    validation-error:
      title: Validation Error
      description: Validation Error
      type: object
      required:
        - message
        - documentation_url
      properties:
        message:
          type: string
        documentation_url:
          type: string
        errors:
          type: array
          items:
            type: object
            required:
              - code
            properties:
              resource:
                type: string
              field:
                type: string
              message:
                type: string
              code:
                type: string
              index:
                type: integer
              value:
                oneOf:
                  - type: string
                    nullable: true
                  - type: integer
                    nullable: true
                  - type: array
                    nullable: true
                    items:
                      type: string
  responses:
    validation_failed:
      description: Validation failed, or the endpoint has been spammed.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/validation-error'
  parameters:
    org:
      name: org
      description: The organization name. The name is not case sensitive.
      in: path
      required: true
      schema:
        type: string
    owner:
      name: owner
      description: The account owner of the repository. The name is not case sensitive.
      in: path
      required: true
      schema:
        type: string
    repo:
      name: repo
      description: >-
        The name of the repository without the `.git` extension. The name is not
        case sensitive.
      in: path
      required: true
      schema:
        type: string
  examples:
    interaction-limit-response:
      value:
        limit: collaborators_only
        origin: organization
        expires_at: '2018-08-17T04:18:39Z'
    interaction-limit-2:
      value:
        limit: collaborators_only
        origin: repository
        expires_at: '2018-08-17T04:18:39Z'
    interaction-limit-user:
      value:
        limit: collaborators_only
        origin: user
        expires_at: '2018-08-17T04:18:39Z'
  x-stackQL-resources:
    orgs:
      id: github.interactions.orgs
      name: orgs
      title: Orgs
      methods:
        get_restrictions_for_org:
          operation:
            $ref: '#/paths/~1orgs~1{org}~1interaction-limits/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        set_restrictions_for_org:
          operation:
            $ref: '#/paths/~1orgs~1{org}~1interaction-limits/put'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        remove_restrictions_for_org:
          operation:
            $ref: '#/paths/~1orgs~1{org}~1interaction-limits/delete'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
      sqlVerbs:
        select:
          - $ref: >-
              #/components/x-stackQL-resources/orgs/methods/get_restrictions_for_org
        insert: []
        update: []
        delete:
          - $ref: >-
              #/components/x-stackQL-resources/orgs/methods/remove_restrictions_for_org
        replace:
          - $ref: >-
              #/components/x-stackQL-resources/orgs/methods/set_restrictions_for_org
    repos:
      id: github.interactions.repos
      name: repos
      title: Repos
      methods:
        get_restrictions_for_repo:
          operation:
            $ref: '#/paths/~1repos~1{owner}~1{repo}~1interaction-limits/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        set_restrictions_for_repo:
          operation:
            $ref: '#/paths/~1repos~1{owner}~1{repo}~1interaction-limits/put'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        remove_restrictions_for_repo:
          operation:
            $ref: '#/paths/~1repos~1{owner}~1{repo}~1interaction-limits/delete'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
      sqlVerbs:
        select:
          - $ref: >-
              #/components/x-stackQL-resources/repos/methods/get_restrictions_for_repo
        insert: []
        update: []
        delete:
          - $ref: >-
              #/components/x-stackQL-resources/repos/methods/remove_restrictions_for_repo
        replace:
          - $ref: >-
              #/components/x-stackQL-resources/repos/methods/set_restrictions_for_repo
    user:
      id: github.interactions.user
      name: user
      title: User
      methods:
        get_restrictions_for_authenticated_user:
          operation:
            $ref: '#/paths/~1user~1interaction-limits/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        set_restrictions_for_authenticated_user:
          operation:
            $ref: '#/paths/~1user~1interaction-limits/put'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        remove_restrictions_for_authenticated_user:
          operation:
            $ref: '#/paths/~1user~1interaction-limits/delete'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
      sqlVerbs:
        select:
          - $ref: >-
              #/components/x-stackQL-resources/user/methods/get_restrictions_for_authenticated_user
        insert: []
        update: []
        delete:
          - $ref: >-
              #/components/x-stackQL-resources/user/methods/remove_restrictions_for_authenticated_user
        replace:
          - $ref: >-
              #/components/x-stackQL-resources/user/methods/set_restrictions_for_authenticated_user
servers:
  - url: https://api.github.com
